version: '3.3'

services:

  prometheus:
    build:
      context: ./dockerfiles/prometheus/
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/var/lib/prometheus
    networks:
      - backend
    ports:
      - 9090:9090

  blackbox-exporter:
    build:
      context: ./dockerfiles/blackbox-exporter/
    hostname: '{{.Node.ID}}'
    volumes:
      - /proc:/usr/proc
      - /sys:/usr/sys
      - /:/rootfs
    # deploy:
    #   mode: global
    networks:
      - backend
    ports:
      - 9115:9115

  alertmanager:
    build:
      context: ./dockerfiles/alertmanager/
    volumes:
      - ./conf/alertmanager/:/etc/alertmanager/
    networks:
      - backend
    ports:
      - 9093:9093

  # prometheus-teams:
  #   image: bzon/prometheus-msteams:v1.1.4
  #   hostname: '{{.Node.ID}}'
  #   networks:
  #     - backend
  #   environment:
  #     - TEAMS_INCOMING_WEBHOOK_URL="https://outlook.office.com/webhook/d722f014-f51d-412a-8d33-6ad676145ae2@ddacce4a-f736-45e1-9c8c-efbe236c4706/IncomingWebhook/f22af8fc0baf4e78abf6e8a7895973af/c0de56fe-5b14-4ff5-9925-3e728dd8f1b0"
  #     - TEAMS_REQUEST_URI=alertmanager
  #   ports:
  #     - 2000:2000

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    # deploy:
    #   mode: global
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - grafana.config
    networks:
      - backend
      - frontend
    ports:
      - 3000:3000

networks:
  frontend:
  backend:

volumes:
    prometheus_data:
    grafana_data:
