global:
  resolve_timeout: 5s

route:
  group_by: ['alertname']
  repeat_interval: 30s
  group_interval: 30s
  group_wait: 2s
  receiver: 'prom2teams'

receivers:
- name: 'prom2teams'
  webhook_configs:
  - url: http://prom2teams:8089/v2/https://outlook.office.com/webhook/d722f014-f51d-412a-8d33-6ad676145ae2@ddacce4a-f736-45e1-9c8c-efbe236c4706/IncomingWebhook/b80b7f79bfb94368968dd79f82042b53/c0de56fe-5b14-4ff5-9925-3e728dd8f1b0
    send_resolved: true

### IF YOU WANT USE SLACK, UNCOMMENT THE LINES BELLOW AND COMMENT THE LINES ABOVE
### REMEMBER, IF YOU WANT USE SLACK, YOU DON'T NEED THE MONGO AND ROCKETCHAT SERVICES, SO YOU CAN REMOVE THIS SERVICES FROM docker-compose FILE.
### PUT YOUR INFORMATION AS USERNAME, CHANNEL AND THE INCOMMING WEBHOOK

#route:
#   receiver: 'slack'
#
#receivers:
#   - name: 'slack'
#     slack_configs:
#        - send_resolved: true
#          username: 'YOUR USERNAME'
#          channel: '#YOURCHANNEL'
#          api_url: 'INCOMMING WEBHOOK'

# route:
#     repeat_interval: 30m
#     group_interval: 30m
#     receiver: 'rocketchat'
#
# receivers:
#     - name: 'rocketchat'
#       webhook_configs:
#           - send_resolved: false
#             url: 'INCOMING_WEBHOOK'
