global:
  resolve_timeout: 5m

# https://outlook.office.com/webhook/d722f014-f51d-412a-8d33-6ad676145ae2@ddacce4a-f736-45e1-9c8c-efbe236c4706/IncomingWebhook/f22af8fc0baf4e78abf6e8a7895973af/c0de56fe-5b14-4ff5-9925-3e728dd8f1b0

receivers:
- name: 'prometheus-teams'
  webhook_configs:
  - url: 'https://outlook.office.com/webhook/d722f014-f51d-412a-8d33-6ad676145ae2@ddacce4a-f736-45e1-9c8c-efbe236c4706/IncomingWebhook/f22af8fc0baf4e78abf6e8a7895973af/c0de56fe-5b14-4ff5-9925-3e728dd8f1b0'
    send_resolved: true
  # - url: 'http://prometheus-teams:2000/alertmanager'

route:
  repeat_interval: 5m
  group_interval: 5m
  group_wait: 30s
  receiver: 'prometheus-teams'

### IF YOU WANT USE SLACK, UNCOMMENT THE LINES BELLOW AND COMMENT THE LINES ABOVE
### REMEMBER, IF YOU WANT USE SLACK, YOU DON'T NEED THE MONGO AND ROCKETCHAT SERVICES, SO YOU CAN REMOVE THIS SERVICES FROM docker-compose FILE.
### PUT YOUR INFORMATION AS USERNAME, CHANNEL AND THE INCOMMING WEBHOOK

#route:
#   receiver: 'slack'
#
#receivers:
#   - name: 'slack'
#     slack_configs:
#        - send_resolved: true
#          username: 'YOUR USERNAME'
#          channel: '#YOURCHANNEL'
#          api_url: 'INCOMMING WEBHOOK'

# route:
#     repeat_interval: 30m
#     group_interval: 30m
#     receiver: 'rocketchat'
#
# receivers:
#     - name: 'rocketchat'
#       webhook_configs:
#           - send_resolved: false
#             url: 'INCOMING_WEBHOOK'
