global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'giropops-monitoring'
rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox-exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://api.alliance.saraivaeducacao.com.br/api/v1/health # alliance-prod
          - http://api.saraivadigital.com.br/ping # api-production
          - http://apppay.saraivaeducacao.com.br/api/health # app-pay-prod
          - http://blog.saraivaeducacao.com.br # blog-saraivaeducacao-prod
          - http://campuslab.com.br/api/health # campus-lab-prod
          - http://paineljur.com.br
          - http://cms.campuslab.com.br # cms-campuslab-prod
          - http://api.jeyloo.somoseditoras.com.br/api/health # jeyloo-back-prod
          - http://jurisprudencias.saraivaconecta.com.br/public/liveness # jurisprudence-prod
          - http://metabase.campuslab.com.br # metabase-prod
          - http://grafana.saraivaeducacao.com.br # monitoring
          - http://v1.primeirafase.saraivaaprova.com.br/users/sign_in # primeira-fase-prod
          - http://solucoes.prod.con.appprova.com.br/users/sign_in # primeira-fase-prod, solucoes-prod-ing, solucoes-prod-con
          - http://oab.saraivaaprova.com.br # primeira-fase-prod
          - http://campuslab.saraivaaprova.com.br # primeira-fase-prod
          - http://saraivaaprova.com.br # saraiva-aprova-dashboard-prod
          - http://skuld.somoseditoras.com.br # skuld-prod
          - http://gcp.skuld.somoseditoras.com.br # skuld-prod
          - http://any.enade.saraivaeducacao.com.br # solucoes-prod-con
          - http://concluinte.solucoes.solucoesuniversitarias.com.br. # solucoes-prod-con
          - http://any.nivelamento.saraivaeducacao.com.br # solucoes-prod-ing
          - http://ingressante.solucoes.solucoesuniversitarias.com.br. # solucoes-prod-ing
          - http://srp.somoseditoras.com.br/health # somos-reverse-proxy-prod
          - http://sputnik.saraivaeducacao.com.br/v1/health-check # sputnik-prod
          - http://traefik.aws.appprova.com.br/ping # traefik-prod
          - http://traefik.aws.saraivaeducacao.com.br/ping # traefik-prod
          - http://traefik.gcp.campuslab.com.br/ping # traefik-prod
          - http://warden.saraivaeducacao.com.br/api/health # warden-prod
          - http://stg.api.alliance.saraivaeducacao.com.br/api/v1/health # alliance-stg
          - http://api.homolog.equipe.ninja/ping # api-homolog
          - http://stg.apppay.saraivaeducacao.com.br/api/health # app-pay-stg
          - http://stg.blog.saraivaeducacao.com.br # blog-saraivaeducacao-stg
          - http://homolog.campuslab.com.br/api/health # campus-lab-hml
          - http://stg.campuslab.com.br/api/health # campus-lab-stg
          - http://stg.paineljur.com.br
          - http://cmscampuslab.staging.equipe.ninja # cms-campuslab-stg
          - http://api.jeyloo.homolog.equipe.ninja/api/health # jeyloo-back-stg
          - http://stg.jurisprudencias.saraivaconecta.com.br/public/liveness # jurisprudence-stg
          - http://stg.grafana.saraivaeducacao.com.br # monitoring
          - http://any.pf.homolog.equipe.ninja # primeira-fase-stg
          - http://any.pf.homolog.saraivaaprova.com.br # primeira-fase-stg
          - http://app.homolog.saraivaaprova.com.br # primeira-fase-stg
          - http://stg.saraivaaprova.com.br # saraiva-aprova-dashboard-stg
          - http://skuld.homolog.equipe.ninja # skuld-stg
          - http://api.skuld.homolog.equipe.ninja # skuld-stg
          - http://any.su.homolog.equipe.ninja # solucoes-stg
          - http://any.stg.solucoesuniversitarias.com.br # solucoes-stg
          - http://srp.homolog.equipe.ninja/health # somos-reverse-proxy-stg
          - http://sputnik.stg.saraivaeducacao.com.br/v1/health-check # sputnik-stg
          - http://stg.traefik.aws.appprova.com.br/ping # traefik-stg
          - http://stg.traefik.aws.saraivaeducacao.com.br/ping # traefik-stg
          - http://stg.traefik.gcp.campuslab.com.br/ping # traefik-stg
          - http://stg.warden.saraivaeducacao.com.br/api/health # warden-stg
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    dns_sd_configs:
    - names:
      - 'tasks.blackbox-exporter'
      type: 'A'
      port: 9115

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  # - job_name: 'netdata'
  #   metrics_path: '/api/v1/allmetrics'
  #   params:
  #     format: [prometheus]
  #   honor_labels: true
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['YOUR_NETDATA_IP:19999']
